CREATE TABLE public.hubble_attendances_shifts_shifts
(
    id integer,
    name character varying COLLATE pg_catalog."default",
    code character varying COLLATE pg_catalog."default",
    active boolean DEFAULT true,
    shift_start_time time without time zone,
    shift_start_days_offset integer,
    shift_end_time time without time zone,
    shift_end_days_offset integer,
    pay_start_time time without time zone,
    pay_start_days_offset integer,
    ot_mode integer,
    break_mode integer,
    paid_after_end_time boolean DEFAULT false,
    pay_stop_after_hours numeric,
    pay_stop_after_time time without time zone,
    pay_stop_after_days_offset integer,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    working_days numeric DEFAULT 1.0,
    custom_basic double precision,
    basic_multiplier double precision,
    basic_multiplier_reference integer,
    working_hours numeric,
    custom_holiday double precision,
    holiday_multiplier double precision,
    holiday_multiplier_reference integer,
    holiday_work_required boolean NOT NULL DEFAULT false,
--     CONSTRAINT hubble_attendances_shifts_shifts_pkey PRIMARY KEY (id)
)