apiVersion: v1
kind: Secret
metadata:
  name: airflow-hubble
type: Opaque
data:
  # must encode it by doing < echo -n "actual_value_of_secret_key" | base64 >
  # check encoding by doing < echo "encoded_value" | base64 -D >
  # update secret file using < kubectl apply -f ./secret.yaml >
  aws_access_key_id: 1234=
  aws_secret_access_key: 123414=
  prod_pguser: q3123213=
  prod_pgpass: 13123=
  dev_pguser: asdad
  dev_pgpass: asdad
  redshift_user: adasdad==
  redshift_pass: asdasdafafaf