
create table hubble_salaries_ir8as_forms
(
"client_server_id" smallint,
"id" integer,
"ir8as_profile_id" integer,
"unique_entity_number" varchar(15),
"id_type" integer,
"nin_number" varchar(13),
"name" varchar(57),
"birth_date" date,
"sex" integer,
"nationality" varchar(15),
"designation" varchar(1),
"bank" integer,
"commence_date" date,
"termination_date" date,
"address_type" integer,
"block_no" varchar(1),
"st_name" varchar(1),
"level_no" varchar(1),
"unit_no" varchar(1),
"postal_code_l" varchar(1),
"address_line1" varchar(45),
"address_line2" varchar(45),
"address_line3" varchar(18),
"postal_code_c" varchar(10),
"country" varchar(1),
"gross_salary" numeric,
"bonus_salary" numeric,
"bonus_declaration_date" date,
"director_fee" numeric,
"director_fee_approved_date" date,
"s45_applicable" boolean,
"transport_allowance" numeric,
"entertainment_allowance" numeric,
"other_allowance" numeric,
"gross_commission_amount" numeric,
"gross_commission_start_date" date,
"gross_commission_end_date" date,
"gross_commission_indicator" integer,
"pension" numeric,
"gratuity" numeric,
"notice_pay" numeric,
"ex_gratia_payment" numeric,
"other_lump_sum_amount" numeric,
"loss_of_office_compensation" numeric,
"compensation_approval" boolean,
"compensation_approval_date" date,
"retirement_fund" varchar(1),
"retirement_fund_up_to_92" numeric,
"retirement_fund_from_93" numeric,
"employer_contribution_without_tax_concession" numeric,
"excess_cpf_contribution" numeric,
"gain_from_esop_after_2003" numeric,
"gain_from_esop_before_2003" numeric,
"benefits_in_kind_value" numeric,
"exempt_or_remission_indicator" integer,
"exempt_or_remission_amount" numeric,
"tax_borne_by_employer" integer,
"tax_borne_by_employer_amount" numeric,
"tax_borne_by_employee_amount" numeric,
"cpf" numeric,
"designated_pension_or_provident_fund_name" varchar(33),
"donation" numeric,
"mbf_contribution" numeric,
"insurance" numeric,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
primary key ("client_server_id", "id")
)
compound sortkey("client_server_id", "id")
