
create table hubble_workforces_profiles
(
"client_server_id" smallint,
"id" integer,
"user_id" integer,
"name" varchar(91),
"gender" varchar(9),
"birth_date" date,
"other_race" varchar(25),
"other_religion" varchar(18),
"marital_status" varchar(13),
"passport_number" varchar(27),
"passport_expiry_date" date,
"nationality" varchar(37),
"nin_number" varchar(33),
"email" varchar(61),
"phone_number" varchar(42),
"address" varchar(300),
"code" varchar(16),
"commence_date" date,
"termination_date" date,
"termination_reason" varchar(517),
"remarks" varchar(1),
"archival_group" integer,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"has_profile" boolean,
"department_id" integer,
"photo" varchar(73),
"fr_photo" varchar(73),
"company_id" integer,
"race" integer,
"religion" integer,
"dialect" integer,
"other_dialect" varchar(16),
"country_of_birth" varchar(21),
"resident_status" integer,
"national_service" integer,
"spr_issue_date" date,
"first_hired_date" date,
"construction_hired_date" date,
"postal_code" varchar(12),
"room_number" varchar(67),
"check_in_date" date,
"check_out_date" date,
"foreign_residential_address" varchar(106),
"foreign_contact_no" varchar(49),
"trade_id" integer,
"payment_mode" integer,
"medical_history" varchar(357),
"levy_id" integer,
"bank_code" varchar(16),
"branch_no" varchar(13),
"account_no" varchar(24),
"account_name" varchar(73),
"accommodation_id" integer,
"confirmation_date" date,
"division_id" integer,
primary key ("client_server_id", "id")
)
compound sortkey("client_server_id", "id")
