
create table hubble_salaries_payrolls_employee_payments
(
"client_server_id" smallint,
"id" integer,
"payment_id" integer,
"employee_id" integer,
"payment_method" varchar(1),
"basic_payment_date" date,
"overtime_payment_date" date,
"adjustments_payment_date" date,
"basic_payment_mode" varchar(16),
"overtime_payment_mode" varchar(16),
"adjustments_payment_mode" varchar(16),
"payment_type" integer,
"basic_payment_start_date" date,
"overtime_payment_start_date" date,
"adjustments_payment_start_date" date,
"basic_payment_end_date" date,
"overtime_payment_end_date" date,
"adjustments_payment_end_date" date,
"is_following_global_setting" boolean,
"basic_advance_payment_type" integer,
"overtime_advance_payment_type" integer,
"adjustments_advance_payment_type" integer,
"basic_advance_payment_amount" numeric,
"overtime_advance_payment_amount" numeric,
"adjustments_advance_payment_amount" numeric,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"payment_mode" integer,
"total_amount" numeric,
"is_including_fpa" boolean,
"fpa_amount" numeric,
"is_basic_payment_end_of_month" boolean,
"is_overtime_payment_end_of_month" boolean,
"is_adjustments_payment_end_of_month" boolean,
"status" integer,
primary key ("client_server_id", "id")
)
compound sortkey("client_server_id", "id")
