
create table hubble_salaries_payrolls_payments
(
"client_server_id" smallint,
"id" integer,
"payment_schedule_id" integer,
"processing_date" date,
"disbursement_date" date,
"name" varchar(36),
"month" integer,
"year" integer,
"payment_type" integer,
"company_id" integer,
"bank_account_id" integer,
"payment_mode" integer,
"basic_advance_payment_type" integer,
"overtime_advance_payment_type" integer,
"adjustments_advance_payment_type" integer,
"basic_advance_payment_amount" numeric,
"overtime_advance_payment_amount" numeric,
"adjustments_advance_payment_amount" numeric,
"basic_payment_start_date" date,
"basic_payment_end_date" date,
"overtime_payment_start_date" date,
"overtime_payment_end_date" date,
"adjustments_payment_start_date" date,
"adjustments_payment_end_date" date,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"payment_template_id" integer,
"is_including_fpa" boolean,
"no_changes_to_template" boolean,
"is_basic_payment_end_of_month" boolean,
"is_overtime_payment_end_of_month" boolean,
"is_adjustments_payment_end_of_month" boolean,
"status" integer,
primary key ("client_server_id", "id")
)
compound sortkey("client_server_id", "id")
