
create table hubble_tonnages_loads
(
"client_server_id" smallint,
"id" integer,
"project_id" integer,
"vehicle_id" integer,
"weight_in" integer,
"weight_out" integer,
"load_time" timestamp without time zone,
"driver_signature" varchar(1),
"client_signature" varchar(1),
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"weight_in_time" timestamp without time zone,
"start_time" timestamp without time zone,
"load_full" boolean,
"remarks" varchar(1),
"bin_location" varchar(1),
"start_latitude" double precision,
"start_longitude" double precision,
"load_latitude" double precision,
"load_longitude" double precision,
"weight_out_latitude" double precision,
"weight_out_longitude" double precision,
"weight_in_latitude" double precision,
"weight_in_longitude" double precision,
"weight_out_time" timestamp without time zone,
"client_name" varchar(1),
"service_type_id" integer,
"bin_serial_in" varchar(1),
"bin_serial_out" varchar(1),
"dump_bin_serial_number" varchar(1),
"is_dropping_bin" boolean,
"dumping_ground_id" integer,
"unable_to_perform" boolean,
"driver_name" varchar(1),
"drop_latitude" numeric,
"drop_longitude" numeric,
"drop_time" varchar(8),
"dropping_bin_signature" varchar(1),
"dropping_bin_client_name" varchar(1),
primary key ("client_server_id", "id")
)
compound sortkey("client_server_id", "id")
