
create table hubble_workforces_profiles
(
"client_server_id" smallint,
"id" integer,
"user_id" integer,
"name" character varying,
"gender" character varying,
"birth_date" date,
"other_race" character varying,
"other_religion" character varying,
"marital_status" character varying,
"passport_number" character varying,
"passport_expiry_date" date,
"nationality" character varying,
"nin_number" character varying,
"email" character varying,
"phone_number" character varying,
"address" character varying,
"code" character varying,
"commence_date" date,
"termination_date" date,
"termination_reason" text,
"remarks" text,
"archival_group" integer,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"has_profile" boolean,
"department_id" integer,
"photo" character varying,
"fr_photo" character varying,
"company_id" integer,
"race" integer,
"religion" integer,
"dialect" integer,
"other_dialect" character varying,
"country_of_birth" character varying,
"resident_status" integer,
"national_service" integer,
"spr_issue_date" date,
"first_hired_date" date,
"construction_hired_date" date,
"postal_code" character varying,
"room_number" character varying,
"check_in_date" date,
"check_out_date" date,
"foreign_residential_address" character varying,
"foreign_contact_no" character varying,
"trade_id" integer,
"payment_mode" integer,
"medical_history" character varying,
"levy_id" integer,
"bank_code" character varying,
"branch_no" character varying,
"account_no" character varying,
"account_name" character varying,
"accommodation_id" integer,
"confirmation_date" date,
"division_id" integer
)
