
create table hubble_salaries_ir8as_forms
(
"client_server_id" smallint,
"id" integer,
"ir8as_profile_id" integer,
"unique_entity_number" character varying,
"id_type" integer,
"nin_number" character varying,
"name" character varying,
"birth_date" date,
"sex" integer,
"nationality" character varying,
"designation" character varying,
"bank" integer,
"commence_date" date,
"termination_date" date,
"address_type" integer,
"block_no" character varying,
"st_name" character varying,
"level_no" character varying,
"unit_no" character varying,
"postal_code_l" character varying,
"address_line1" character varying,
"address_line2" character varying,
"address_line3" character varying,
"postal_code_c" character varying,
"country" character varying,
"gross_salary" numeric,
"bonus_salary" numeric,
"bonus_declaration_date" date,
"director_fee" numeric,
"director_fee_approved_date" date,
"s45_applicable" boolean,
"transport_allowance" numeric,
"entertainment_allowance" numeric,
"other_allowance" numeric,
"gross_commission_amount" numeric,
"gross_commission_start_date" date,
"gross_commission_end_date" date,
"gross_commission_indicator" integer,
"pension" numeric,
"gratuity" numeric,
"notice_pay" numeric,
"ex_gratia_payment" numeric,
"other_lump_sum_amount" numeric,
"loss_of_office_compensation" numeric,
"compensation_approval" boolean,
"compensation_approval_date" date,
"retirement_fund" character varying,
"retirement_fund_up_to_92" numeric,
"retirement_fund_from_93" numeric,
"employer_contribution_without_tax_concession" numeric,
"excess_cpf_contribution" numeric,
"gain_from_esop_after_2003" numeric,
"gain_from_esop_before_2003" numeric,
"benefits_in_kind_value" numeric,
"exempt_or_remission_indicator" integer,
"exempt_or_remission_amount" numeric,
"tax_borne_by_employer" integer,
"tax_borne_by_employer_amount" numeric,
"tax_borne_by_employee_amount" numeric,
"cpf" numeric,
"designated_pension_or_provident_fund_name" character varying,
"donation" numeric,
"mbf_contribution" numeric,
"insurance" numeric,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone
)
