
create table hubble_tonnages_loads
(
"client_server_id" smallint,
"id" integer,
"project_id" integer,
"vehicle_id" integer,
"weight_in" integer,
"weight_out" integer,
"load_time" timestamp without time zone,
"driver_signature" text,
"client_signature" text,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"weight_in_time" timestamp without time zone,
"start_time" timestamp without time zone,
"load_full" boolean,
"remarks" text,
"bin_location" text,
"start_latitude" double precision,
"start_longitude" double precision,
"load_latitude" double precision,
"load_longitude" double precision,
"weight_out_latitude" double precision,
"weight_out_longitude" double precision,
"weight_in_latitude" double precision,
"weight_in_longitude" double precision,
"weight_out_time" timestamp without time zone,
"client_name" text,
"service_type_id" integer,
"bin_serial_in" text,
"bin_serial_out" text,
"dump_bin_serial_number" text,
"is_dropping_bin" boolean,
"dumping_ground_id" integer,
"unable_to_perform" boolean,
"driver_name" text,
"drop_latitude" numeric,
"drop_longitude" numeric,
"drop_time" time without time zone,
"dropping_bin_signature" text,
"dropping_bin_client_name" text
)
