
create table hubble_face_ids_devices
(
"client_server_id" smallint,
"id" integer,
"java_server_name" character varying,
"serial_number" character varying,
"edition" character varying,
"volume" character varying,
"weigen" character varying,
"lan_ip" character varying,
"gateway" character varying,
"netmask" character varying,
"mac_address" character varying,
"wan_ip" character varying,
"forwarding_port" character varying,
"max_manager_number" integer,
"real_manager_number" integer,
"max_face_register" integer,
"real_face_register" integer,
"max_face_record" integer,
"real_face_record" integer,
"max_employee" integer,
"real_employee" integer,
"max_other" integer,
"real_other" integer,
"model" character varying,
"alg_edition" character varying,
"manager_lock" boolean,
"check_type" integer,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone
)
