
create table hubble_quality_qa_requests
(
"client_server_id" smallint,
"id" integer,
"ref_num" character varying,
"project_id" integer,
"is_joint_inspection" integer,
"joint_subcontractor_id" integer,
"joint_validation" bytea,
"location_x" double precision,
"location_y" double precision,
"subcontractor_id" integer,
"type_id" integer,
"description" character varying,
"dimensions" character varying,
"remedial_action" character varying,
"deadline" date,
"approval_status" integer,
"supervisor_id" integer,
"status" integer,
"manager_remarks" character varying,
"supervisor_remarks" character varying,
"subcontractor_remarks" character varying,
"created_at" timestamp without time zone,
"updated_at" timestamp without time zone,
"floorplan_id" integer,
"defect_reason" character varying,
"soi_ref_number" character varying,
"is_archived" boolean
)
