
create table hubble_workforces_profiles
(
profile_id integer,
profile_user_id integer,
profile_name varchar(64),
profile_gender varchar(8),
profile_birth_date date,
profile_other_race varchar(32),
profile_other_religion varchar(16),
profile_marital_status varchar(16),
profile_passport_number varchar(32),
profile_passport_expiry_date date,
profile_nationality varchar(32),
profile_nin_number varchar(32),
profile_email varchar(64),
profile_phone_number varchar(32),
profile_address varchar(256),
profile_code varchar(16),
profile_commence_date date,
profile_termination_date date,
profile_termination_reason varchar(512),
profile_remarks varchar(256),
profile_archival_group integer,
profile_created_at timestamp without time zone,
profile_updated_at timestamp without time zone,
profile_has_profile boolean,
profile_department_id integer,
profile_photo varchar(64),
profile_fr_photo varchar(64),
profile_company_id integer,
profile_race integer,
profile_religion integer,
profile_dialect integer,
profile_other_dialect varchar(16),
profile_country_of_birth varchar(16),
profile_resident_status integer,
profile_national_service integer,
profile_spr_issue_date date,
profile_first_hired_date date,
profile_construction_hired_date date,
profile_postal_code varchar(8),
profile_room_number varchar(64),
profile_check_in_date date,
profile_check_out_date date,
profile_foreign_residential_address varchar(128),
profile_foreign_contact_no varchar(64),
profile_trade_id integer,
profile_payment_mode integer,
profile_medical_history varchar(256),
profile_levy_id integer,
profile_bank_code varchar(16),
profile_branch_no varchar(16),
profile_account_no varchar(16),
profile_account_name varchar(64),
profile_accommodation_id integer,
profile_confirmation_date date,
profile_division_id integer,
profile_client_id smallint
)
