
create table hubble_attendances_shifts_shifts
(
shift_id integer,
shift_name varchar(64),
shift_code varchar(64),
shift_active boolean,
shift_shift_start_time varchar(8),
shift_shift_start_days_offset integer,
shift_shift_end_time varchar(8),
shift_shift_end_days_offset integer,
shift_pay_start_time varchar(8),
shift_pay_start_days_offset integer,
shift_ot_mode integer,
shift_break_mode integer,
shift_paid_after_end_time boolean,
shift_pay_stop_after_hours numeric,
shift_pay_stop_after_time varchar(8),
shift_pay_stop_after_days_offset integer,
shift_created_at timestamp without time zone,
shift_updated_at timestamp without time zone,
shift_working_days numeric,
shift_custom_basic double precision,
shift_basic_multiplier double precision,
shift_basic_multiplier_reference integer,
shift_working_hours numeric,
shift_custom_holiday double precision,
shift_holiday_multiplier double precision,
shift_holiday_multiplier_reference integer,
shift_holiday_work_required boolean,
shift_client_id smallint
)
